{
	"_Type": "Action.Type.CheckRequiredFields",
	"OnFailure": "/SAPAssetManager/Rules/UserPersonas/UpdateUserPersonaOnFailure.js",
	"OnSuccess": "/SAPAssetManager/Rules/UserPersonas/OverviewUserPersona.js",
    "RequiredFields": ["SwitchPersonaLstPkr"],
	"ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  "
}