{
	"_Type": "Action.Type.Message",
	"Message": "$(L, confirm_cancel)",
    "OKCaption": "$(L,ok)",
    "CancelCaption": "$(L,cancel)",
    "OnOK": "/SAPAssetManager/Rules/Crew/ClearFlagsAndClose.js"
}