{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "CrewListItems",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink": "#ClientData/#Property:CrewListItemReadLink"
    },
    "Properties": {
        "CatsHours": "#ClientData/#Property:TotalCatsHours"
    },
    "Headers":
	{
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Crew/Header/CrewListCrewId.js"
    },
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  "
}
