{
    "Animated": true,
    "Duration": 2,
    "Message": "$(L,crew_member_removed)",
    "Icon": "",
    "IsIconHidden": false,
    "MaxNumberOfLines": 1,
    "OnSuccess": "/SAPAssetManager/Actions/Page/ClosePage.action",
    "_Type": "Action.Type.ToastMessage"
  }