{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target":
    {
        "EntitySet" : "Confirmations",
        "Service" : "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties":
    {
        "ConfirmationNum" : "#ClientData/#Property:localConfirmationNum",
        "ConfirmationCounter": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GenerateConfirmationCounter.js",
        "PostingDate": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GetPostingDate.js",
        "StartDate": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GetDate.js",
        "StartTime": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GetStartTime.js",
        "StartTimeStamp": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GetStartTimeStamp.js",
        "SubOperation": "#Property:SubOperation",
        "VarianceReason": "#Property:VarianceReason",
        "AccountingIndicator": "#Property:AccountingIndicator",
        "ActivityType": "#Property:ActivityType",
        "ActualDuration": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GetDuration.js",
        "ActualDurationUOM": "MIN",
        "ActualWork": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GetDuration.js",
        "ActualWorkUOM": "MIN",
        "CompleteFlag": "",
        "Description": "",
        "FinalConfirmation": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GetIsFinalConfirmation.js",
        "FinishDate": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GetEndDate.js",
        "FinishTime": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GetEndTime.js",
        "Operation": "#Property:Operation",
        "OrderID": "#Property:OrderID",
        "PersonnelNumber": "/SAPAssetManager/Rules/TimeSheets/CreateUpdate/TimeSheetCreateUpdatePersonnelNumber.js",
        "Plant": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GetPlant.js",
        "ReverseIndicator": "",
        "CreatedDate": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GetCreatedDate.js",
        "CreatedTime": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/GetCreatedTime.js",
        "OrderType": "#Property:OrderType"
    },
    "Headers": {
        "OfflineOData.RemoveAfterUpload": "true",
        "OfflineOData.TransactionID": "#ClientData/#Property:localConfirmationNum"
    },
    "CreateLinks": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/CreateLinks.js",
    "ValidationRule": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/OnCommit/IsValidConfirmation.js",
    "OnSuccess": "/SAPAssetManager/Rules/ClockInClockOut/Confirmations/ConfirmationSuccess.js"
}