{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Confirmations/ConfirmationsListView.page",
    "ShowActivityIndicator" : true,
    "ActivityIndicatorText" : " "
}
