{
    "Headers": {
        "OfflineOData.NonMergeable": true
    },
    "Properties": {
        "ObjectType": "/SAPAssetManager/Rules/MobileStatus/MobileStatusSetCompleteObjectType.js",
        "ObjectKey": "/SAPAssetManager/Rules/MobileStatus/MobileStatusSetCompleteObjectKey.js",
        "MobileStatus": "/SAPAssetManager/Rules/MobileStatus/MobileStatusCompleted.js",
        "EffectiveTimestamp": "/SAPAssetManager/Rules/DateTime/EndDateTime.js",
        "CreateUserGUID": "/SAPAssetManager/Rules/UserPreferences/UserPreferencesUserGuidOnCreate.js",
        "CreateUserId": "/SAPAssetManager/Rules/MobileStatus/GetSAPUserId.js"
    },
    "Target": {
        "EntitySet": "PMMobileStatuses",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink" : "/SAPAssetManager/Rules/MobileStatus/MobileStatusSetCompleteReadLink.js"
    },
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "ActionResult" : {"_Name" : "MobileStatusSetComplete"}
}
