{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target": {
        "EntitySet": "S4ServiceConfirmationItems",
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties": {},
    "Headers": {
        "OfflineOData.RemoveAfterUpload": "true",
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/ServiceConfirmations/CreateUpdate/Data/GetServiceConfirmationLocalID.js"
    },
    "CreateLinks": [
        {
            "Property": "S4ServiceConfirmation_Nav",
            "Target": {
                "EntitySet": "S4ServiceConfirmations",
                "ReadLink": "/SAPAssetManager/Rules/ServiceConfirmations/CreateUpdate/GetServiceConfirmationLink.js"
            }
        }
    ],
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  "
}
