{
    "_Type": "Action.Type.CheckRequiredFields",
    "RequiredFields": "/SAPAssetManager/Rules/ServiceConfirmations/CreateUpdate/ServiceConfirmationRequiredFields.js",
    "ValidationRule": "/SAPAssetManager/Rules/ServiceConfirmations/CreateUpdate/ServiceConfirmationItemCreateUpdateValidation.js",
    "OnFailure": "/SAPAssetManager/Rules/Common/UpdateRequiredFailed.js",
    "OnSuccess": "/SAPAssetManager/Rules/ServiceConfirmations/CreateUpdate/ServiceConfirmationItemOnCommit.js"
}