{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Target": {
		"EntitySet": "MyEquipGeometries",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"Properties": {
		"ObjectType": "IEQ",
		"ObjectKey": "#Page:EquipmentDetailsPage/#Property:EquipId",
		"EquipId": "#Page:EquipmentDetailsPage/#Property:EquipId"
	},
	"Headers": {
        "OfflineOData.RemoveAfterUpload": "true",
		"Transaction.Ignore": "true",
        "OfflineOData.TransactionID": "#Page:EquipmentDetailsPage/#Property:EquipId"
    },
	"RequestOptions": {
		"UnmodifiableRequest": true,
		"SendEmptyUpdate": true
	},
	"CreateLinks": [{
			"Property" : "Geometry",
			"Target":
			{
				"EntitySet" : "Geometries",
				"ReadLink" : "/SAPAssetManager/Rules/Geometries/GeometryReadLink.js"
			}
		},
		{
			"Property" : "Equip_Nav",
			"Target":
			{
				"EntitySet" : "MyEquipments",
				"ReadLink" : "#Page:EquipmentDetailsPage/#Property:@odata.readLink"
			}
		}
	],
	"OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action"
}