{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target":
	{
		"EntitySet" : "MyEquipments",
		"Service" : "/SAPAssetManager/Services/AssetManager.service",
		"ReadLink" : "#Page:EquipmentDetailsPage/#Property:@odata.readLink"
	},
	"CreateLinks":
    [{
        "Property": "Geometry_Nav",
		"Target":
		{
			"EntitySet" : "Geometries", 
			"ReadLink" : "/SAPAssetManager/Rules/Geometries/GeometryReadLink.js"
		}
    }],
	"OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/UpdateEntityFailureMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText" : "  "
}