{
    "Actions": [
        "/SAPAssetManager/Actions/Equipment/CreateUpdate/EquipmentCreateUpdateNav.action"
    ],
    "OnSuccess": "/SAPAssetManager/Actions/Equipment/CreateUpdate/EquipmentCreateStatus.action",
    "OnFailure" : "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnFailure.js",
    "Target": {
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "_Type": "Action.Type.ODataService.ChangeSet"
} 