{
    "_Type": "Action.Type.Filter",
    "PageToOpen": "/SAPAssetManager/Pages/WCM/OperationalItems/OperationalItemsListFilter.page",
    "Filterable": "#Page:OperationalItemsListViewPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}