{
    "Message": "$(L, confirm_cancel)",
    "OKCaption": "$(L,continue_text)",
    "CancelCaption": "$(L,cancel)",
    "OnOK": "/SAPAssetManager/Rules/Inventory/PhysicalInventory/PhysicalInventoryCreateListNavAfterCancel.js",
    "_Type": "Action.Type.Message"
}