{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "PhysicalInventoryDocItems",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink": "{Temp_PIItemReadlink}"
    },
    "Properties": {
        "EntryQuantity": "{Temp_EntryQuantity}",
        "ZeroCount" : "{Temp_ZeroCount}",
        "Item": "{Temp_Item}",
        "Material": "{Temp_Material}",
        "EntryUOM": "{Temp_EntryUOM}",
        "Batch": "{Temp_Batch}"
    },
    "Headers": {
        "OfflineOData.TransactionID": "#Property:TempHeader_Key"
    },
    "RequestOptions": {
        "UpdateMode": "Replace"
    },
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action"
}