{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target": 
    {
        "EntitySet" : "PhysicalInventoryDocHeaders",
        "Service" : "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties":
    {
        "PhysInvDoc" : "/SAPAssetManager/Rules/Inventory/PhysicalInventory/PhysicalInventoryDocumentID.js",
        "FiscalYear": "/SAPAssetManager/Rules/Inventory/PhysicalInventory/PhysicalInventoryDocumentFiscalYear.js",
        "Plant": "#Control:PlantLstPkr/#SelectedValue",
        "StorLocation": "#Control:StorageLocationPicker/#SelectedValue",
        "DocumentDate": "/SAPAssetManager/Rules/Inventory/PhysicalInventory/PhysicalInventoryDocumentDate.js",
        "CountDate": "/SAPAssetManager/Rules/Inventory/PhysicalInventory/PhysicalInventoryDocumentDate.js",
        "UserName": "/SAPAssetManager/Rules/Inventory/PhysicalInventory/PhysicalInventoryCreateUserName.js",
        "Physinventref":  "#Control:PhysInventoryReferenceProperty/#Value",
        "PhysInvNo": "#Control:PhysInventoryProperty/#Value",
        "CountOnCreate": "X"
    },
    "Headers": {
        "OfflineOData.RemoveAfterUpload": "true",
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Inventory/PhysicalInventory/PhysicalInventoryCreateTransactionID.js"
    },
    "ShowActivityIndicator": true
}