{
    "Animated": true,
    "Duration": 2,
    "Message": "$(L,operation_assigned_message)",
    "IsIconHidden": false,
    "MaxNumberOfLines": 1,
    "_Type": "Action.Type.ToastMessage",
    "OnSuccess": "/SAPAssetManager/Actions/Page/ClosePage.action"
  }