{
    "Actions":
    [
        "/SAPAssetManager/Actions/Supervisor/Assign/WorkOrderOrOperationTransferAssignPerson.action"
    ],
    "Target":
    {
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/UpdateEntityFailureMessage.action",
    "ShowActivityIndicator": true,
    "_Type": "Action.Type.ODataService.ChangeSet"
}