{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/BusinessPartners/BusinessPartnerDetails.page",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  "
}
