{
	"_Type": "Action.Type.CheckRequiredFields",
	"RequiredFields": [
		"passcode"
	],
	"OnSuccess": "/SAPAssetManager/Actions/OData/DigitalSignature/CreateDigitalSignature.action",
	"OnFailure": "/SAPAssetManager/Rules/DigitalSignature/SetPasdcodeError.js"
}