{
	"_Type": "Action.Type.BannerMessage",
	"Message": "#ActionResults:result/#Property:error",
	"ActionLabel": "Tap this banner to try again.",
	"OnActionLabelPress": "/SAPAssetManager/Actions/OData/DigitalSignature/CreateServiceProgressBanner.action",
	"DismissBannerOnAction": true,
	"Duration": 9999
}