{
	"_Type": "Action.Type.ProgressBanner",
	"Message": "$(L, connecting_to_online_service)",
	"OnSuccess":"/SAPAssetManager/Actions/OData/DigitalSignature/CreateOnlineDigitalSignatureService.action",
	"ActionLabel": "$(L, tap_to_cancel)",
	"OnActionLabelPress": "/SAPAssetManager/Actions/Page/CancelPage.action",
	"DismissBannerOnAction": true,
	"CompletionMessage": "$(L, connected_message)",
	"CompletionTimeout": 2
}