{
	"_Type": "Action.Type.ODataService.DeleteEntity",
	"Target": {
		"Service": "/SAPAssetManager/Services/AssetManager.service",
		"EntitySet": "UserPreferences",
		"ReadLink": "#ClientData/#Property:SignatureReadLink"
	}
}