{
    "_Type": "Action.Type.ODataService.DeleteEntity",
    "Target": {
        "EntitySet": "UserPreferences",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink": "/SAPAssetManager/Rules/DigitalSignature/UserPrefsDeviceGUIDReadLink.js"
    },
     "RequestOptions": {
		"UploadCategory": "TOTPDevicesUpdates"
	},
    "OnSuccess": "/SAPAssetManager/Rules/DigitalSignature/TOTPPartialUploadAfterDelete.js",
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/DeleteEntityFailureMessage.action"
}