{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Target": {
		"EntitySet": "UserPreferences",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"Properties": {
		"UserGuid": "/SAPAssetManager/Rules/UserPreferences/UserPreferencesUserGuidOnCreate.js",
		"RecordId": "/SAPAssetManager/Rules/UserPreferences/UserPreferencesRecordIdOnCreate.js",
		"PreferenceGroup": "TOTP_DEVICE",
		"PreferenceName": "DeviceGUID",
		"PreferenceValue": "#Application/#AppData/DeviceId"
	},
	"RequestOptions": {
		"UploadCategory": "TOTPDevicesUpdates"
	},
	"OnSuccess": "/SAPAssetManager/Rules/DigitalSignature/TOTPPartialUploadAfterCreate.js",
	"OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action"
}