{
	"Media": "/SAPAssetManager/Rules/Common/RuleStub.js",
  "Target": {
    "EntitySet" : "FSMFormAttachments",
    "Service": "/SAPAssetManager/Services/AssetManager.service"
  },
  "_Type": "Action.Type.ODataService.CreateMedia"
}
