{
	"_Type": "Action.Type.Filter",
	"PageToOpen" : "/SAPAssetManager/Pages/Forms/FSM/FSMFilter.page",
    "Filterable" : "#Page:FSMSmartFormsInstancesListViewPage/#Control:SectionedTable",
    "OnSuccess": "/SAPAssetManager/Rules/Forms/FSM/OnFSMFilterSuccess.js",
    "ActionResult": {
        "_Name": "filterResult"
    }
}