{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target": {
		"EntitySet": "/SAPAssetManager/Globals/EmptyString.global",
		"Service": "/SAPAssetManager/Services/AssetManager.service",
		"ReadLink": ""
	},
	"Properties": {

	}
}   