{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target":
    {
        "EntitySet" : "OnDemandObjects",
        "Service" : "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties":
    {
        "ObjectId" : "",
        "ObjectType": "",
        "Action": ""
    },
    "Headers": {
        "OfflineOData.RemoveAfterUpload": "true"
    }
}