{
	"PopoverItems": [
		{
			"Title": "$(L, add_service_order)",
			"OnPress": "/SAPAssetManager/Rules/ServiceOrders/CreateUpdate/ServiceOrderCreateNav.js"
		},
		{
			"Title" : "/SAPAssetManager/Rules/Notes/NotePopoverSelectionText.js",
			"OnPress": "/SAPAssetManager/Rules/Notes/NoteCreateNav.js",
			"Visible": "/SAPAssetManager/Rules/ServiceOrders/ServiceRequests/Details/IsServiceRequestIsNotCompleted.js"
		},
		{
			"Title" : "$(L,add_reminder)",
			"OnPress" : "/SAPAssetManager/Rules/Reminders/ReminderCreateNav.js",
			"Visible": "/SAPAssetManager/Rules/ServiceOrders/ServiceRequests/Details/IsServiceRequestIsNotCompleted.js"
		},
		{
			"Title": "$(L, add_attachment)",
			"Visible": "/SAPAssetManager/Rules/ServiceOrders/ServiceRequests/Details/IsServiceRequestIsNotCompleted.js",
			"OnPress": "/SAPAssetManager/Rules/Documents/Create/DocumentCreateBDSNav.js"
		}
	],
	"_Type": "Action.Type.PopoverMenu"
}