{
  "_Type": "Action.Type.ODataService.CreateMedia",
  "Target" : {
    "EntitySet" : "Documents",
    "Service" : "/SAPAssetManager/Services/AssetManager.service"
  },
  "Headers" : {
     "slug" : {
        "ObjectLink": "/SAPAssetManager/Rules/Documents/Create/DocumentCreateObjectLink.js",
        "ObjectKey": "/SAPAssetManager/Rules/Documents/Create/DocumentCreateObjectKeyForHeader.js",
        "FileName": "/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateFileName.js",
        "Description": "/SAPAssetManager/Rules/Documents/Create/DocumentCreateDescription.js",
        "OrderID": "/SAPAssetManager/Rules/WorkOrders/OperationWorkOrderId.js",
        "OperationNo": "/SAPAssetManager/Rules/WorkOrders/OperationNo.js"
    }
  },
  "Properties" : {
    "ObjectLink": "/SAPAssetManager/Rules/Documents/Create/DocumentCreateObjectLink.js",
    "ObjectKey": "/SAPAssetManager/Rules/Documents/DocumentTransactionID.js",
    "FileName": "/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateFileName.js",
    "Description": "/SAPAssetManager/Rules/Documents/Create/DocumentCreateDescription.js",
    "MimeType": "/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateMimeType.js"
  },
  "IsOnlineRequest": false,
  "ShowActivityIndicator": true,
  "ActivityIndicatorText" : "  ",
  "Media":"/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateMedia.js",
  "OnFailure": "/SAPAssetManager/Actions/Documents/DocumentCreateFailure.action"
}