{
    "PopoverItems": 
    [{
        "Title": "$(L,save)",
        "OnPress": "/SAPAssetManager/Rules/Documents/DocumentEditorOverwrite.js",
        "Visible" : true
    },
    {
        "Title": "$(L,save_as)",
        "OnPress": "/SAPAssetManager/Actions/Documents/DocumentEditorSaveAsNav.action",
        "Visible" : true
    }],
    "_Type": "Action.Type.PopoverMenu"
}