{
  "_Type": "Action.Type.ODataService.DeleteMedia",
  "Target": {
    "EntitySet": "Documents",
    "Service": "/SAPAssetManager/Services/AssetManager.service",
    "ReadLink": "/SAPAssetManager/Rules/WorkOrders/WorkOrderDocumentDeleteReadLink.js"
  }
}