{
    "Message": "$(L, confirm_cancel)",
    "OKCaption": "$(L,continue_text)",
    "CancelCaption": "$(L,cancel)",
    "OnOK": "/SAPAssetManager/Actions/Page/ClosePage.action",
    "_Type": "Action.Type.Message"
}