{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Target":
	{
		"EntitySet" : "MeasurementDocuments",
		"Service" : "/SAPAssetManager/Services/AssetManager.service"
	},
	"Properties":
	{
        "MeasurementDocNum": "#Property:LocalID",
        "ReadingDate": "/SAPAssetManager/Rules/Measurements/Document/MeasurementDocumentReadingDate.js",
        "ReadingTimestamp": "/SAPAssetManager/Rules/Measurements/Document/MeasurementDocumentReadingTimestamp.js",
        "ReadingTime": "/SAPAssetManager/Rules/Measurements/Document/MeasurementDocumentReadingTime.js",
        "Point": "/SAPAssetManager/Rules/Crew/Vehicles/CrewVehicleOdometerPoint.js",
		"ReadBy": "/SAPAssetManager/Rules/Measurements/Document/MeasurementDocumentReadBy.js",
		"SortField": "#Property:LocalID",
		"ReadingValue" : "/SAPAssetManager/Rules/Crew/Vehicles/CrewVehicleOdometerReadingValue.js",
        "HasReadingValue": "X"
    },
    "Headers":
	{
        "OfflineOData.RemoveAfterUpload": "true",
        "OfflineOData.TransactionID": "#Property:LocalID"
	},
	"CreateLinks":[{
		"Property" : "MeasuringPoint",
		"Target":
		{
			"EntitySet" : "MeasuringPoints",
			"ReadLink" : "/SAPAssetManager/Rules/Crew/Vehicles/CrewVehicleOdometerPointReadLink.js"
		}
	}],
	"OnSuccess" : "/SAPAssetManager/Rules/ApplicationEvents/AutoSync/actions/CreateEntitySuccessMessageWithAutoSave.js",
	"OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action",
	"ValidationRule" : "/SAPAssetManager/Rules/Crew/Vehicles/CrewVehicleCreateUpdateValidation.js"
}