{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/WorkOrders/WorkOrderRelatedHistoriesListView.page",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : " "
}
