{
    "_Type" : "Action.Type.Filter",
    "PageToOpen" : "/SAPAssetManager/Pages/WorkOrders/WorkOrderFilter.page",
    "Filterable" : "#Page:WorkOrdersListViewPage/#Control:SectionedTable",
    "OnSuccess": "/SAPAssetManager/Rules/WorkOrders/WorkOrderListViewFilter.js",
    "ActionResult": {
        "_Name": "filterResult"
    }
}