{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target": {
        "EntitySet": "MyWorkOrderOperationLongTexts",
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties": {
        "OrderId": "#Property:OrderId",
        "OperationNo": "#Property:OperationNo",
        "NewTextString": "#Control:LongTextNote/#Value",
        "TextString": "#Control:LongTextNote/#Value"
    },
    "Headers": {
        "OfflineOData.RemoveAfterUpload": "true",
        "OfflineOData.TransactionID": "#Property:OrderId"
    },
    "OnSuccess": "/SAPAssetManager/Rules/Notes/NoteCreateOnSuccess.js",
    "OnFailure": "/SAPAssetManager/Actions/Notes/NoteCreateFailureMessage.action",
    "CreateLinks": "/SAPAssetManager/Rules/Notes/NoteCreateLinks.js"

}
