{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target": {
        "EntitySet": "/SAPAssetManager/Rules/Notes/NoteGetEntitySet.js",
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties": {
        "NewTextString": "#Control:LongTextNote/#Value",
        "TextString": "#Control:LongTextNote/#Value"
    },
    "Headers": {
        "OfflineOData.RemoveAfterUpload": "true"
    },
    "OnSuccess": "/SAPAssetManager/Rules/Notes/SubOperation/NotificationCreateNoteCreate.js",
    "OnFailure": "/SAPAssetManager/Actions/Notes/NoteCreateFailureMessage.action",
    "CreateLinks": "/SAPAssetManager/Rules/Notes/NoteCreateLinks.js"
}