{
    "_Type": "Action.Type.ODataService.CreateRelatedEntity",
    "Target": {
        "EntitySet": "/SAPAssetManager/Rules/Notes/NoteGetEntitySet.js",
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties": {
        "ConfirmationNum": "#Property:ConfirmationNum",
        "NewTextString": "#Control:DescriptionNote/#Value",
        "TextString": "#Control:DescriptionNote/#Value"
    },
    "ParentLink": {
        "Property": "LongText",
        "Target": {
          "EntitySet": "Confirmations",
          "ReadLink": "{@odata.readLink}"
        }
    },
    "Headers": {
        "OfflineOData.TransactionID": "#Property:ConfirmationNum"
    },
    "OnFailure": "/SAPAssetManager/Actions/Notes/NoteCreateFailureMessage.action"
}