{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/WorkOrders/Operations/PRT/PRTMaterialDetails.page",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  "
}
