{
	"_Type": "Action.Type.PopoverMenu",
	"PopoverItems": [
		{
			"Title": "$(L,add_cause)",
			"OnPress": "/SAPAssetManager/Rules/Notifications/Item/Cause/CreateUpdate/NotificationItemCauseCreateNav.js"
		},
		{
			"Title": "$(L,add_task)",
			"OnPress": "/SAPAssetManager/Rules/Notifications/Item/Task/CreateUpdate/NotificationItemTaskCreateNav.js",
			"Visible": false
		},
		{
			"Title": "$(L,add_activity)",
			"OnPress": "/SAPAssetManager/Rules/Notifications/Item/Activity/CreateUpdate/NotificationItemActivityCreateNav.js",
			"Visible": false
		},
		{
			"Title": "/SAPAssetManager/Rules/Notes/NotePopoverSelectionText.js",
			"OnPress": "/SAPAssetManager/Rules/Notes/NoteCreateNav.js"
		}
	]
}