{
    "Actions":
    	[
            "/SAPAssetManager/Actions/Notifications/Item/NotificationItemTaskCreate.action"
        ],
    "OnSuccess": "/SAPAssetManager/Actions/MobileStatus/MobileStatusNotificationItemTaskSetReceived.action",
    "OnFailure" : "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnFailure.js",
    "Target":
    	{
            "Service": "/SAPAssetManager/Services/AssetManager.service"
        },
    "_Type": "Action.Type.ODataService.ChangeSet"
}