{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target":
	{
		"EntitySet" : "MyNotificationItemTasks",
		"Service" : "/SAPAssetManager/Services/AssetManager.service",
		"ReadLink" : "{@odata.readLink}"
	},
	"Properties":
	{
		"TaskText" : "#Control:DescriptionTitle/#Value",
		"TaskCodeGroup": "/SAPAssetManager/Rules/Notifications/GroupLstPkrValue.js",
		"TaskCode" : "/SAPAssetManager/Rules/Notifications/CodeLstPkrValue.js"
	},
	"Headers":
	{
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Notifications/NotificationItemCauseTaskActivityParentID.js"
    },
	"OnSuccess" : "/SAPAssetManager/Rules/ApplicationEvents/AutoSync/actions/UpdateEntitySuccessMessageWithAutoSave.js",
	"OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/UpdateEntityFailureMessage.action",
	"ValidationRule": "/SAPAssetManager/Rules/Notifications/Task/CreateUpdate/NotificationTaskCreateUpdateValidation.js"
}