{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Target": {
		"EntitySet": "UserPreferences",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"Properties": {
		"UserGuid": "/SAPAssetManager/Rules/UserPreferences/UserPreferencesUserGuidOnCreate.js",
        "RecordId": "/SAPAssetManager/Rules/UserPreferences/UserPreferencesRecordIdOnCreate.js",
        "PreferenceGroup": "EPD",
        "PreferenceName": "",
        "PreferenceValue": ""
	}
}