{
    "OnFailure": "/SAPAssetManager/Actions/Passcode/ChangePasscodeFailure.action",
    "OnSuccess": "/SAPAssetManager/Actions/Passcode/ChangePasscodeSuccess.action",
    "_Type": "Action.Type.ChangeUserPasscode"
}