{
    "Headers": {
        "OfflineOData.NonMergeable": true
    },
    "Properties": {
        "MobileStatus": "/SAPAssetManager/Rules/MobileStatus/MobileStatusCompleted.js",
        "EffectiveTimestamp": "/SAPAssetManager/Rules/DateTime/CurrentDateTime.js"
    },
    "Target": {
        "EntitySet": "PMMobileStatuses",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink" : "/SAPAssetManager/Rules/MobileStatus/MobileStatusReadLink.js"
    },
    "_Type": "Action.Type.ODataService.UpdateEntity"
}