{
    "OnFailure": "/SAPAssetManager/Rules/Common/UpdateRequiredFailed.js",
    "OnSuccess": "/SAPAssetManager/Rules/Meter/CreateUpdate/MeterCreateUpdateChangeSet.js",
    "RequiredFields": [
        "ReasonLstPkr",
        "MeterLstPkr",
        "ConnectionLstPkr"
    ],
    "_Type": "Action.Type.CheckRequiredFields",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  ",
    "ValidationRule": "/SAPAssetManager/Rules/Meter/CreateUpdate/MeterCreateUpdateValidation.js"
}
