{
    "Actions":
	[
        "/SAPAssetManager/Actions/Notifications/CreateUpdate/NotificationCreateUpdateNav.action"
    ],
    "OnSuccess": "/SAPAssetManager/Rules/Notifications/EMP/CreateEMPEntries.js",
    "OnFailure" : "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnFailure.js",
    "Target":
	{
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "_Type": "Action.Type.ODataService.ChangeSet"
}