{
	"PopoverItems": [
		{
			"Title": "$(L,start)",
			"OnPress": "/SAPAssetManager/Rules/Operations/MobileStatus/OperationStartStatus.js"
		},
		{
			"Title": "$(L,transfer)",
			"OnPress": "/SAPAssetManager/Rules/Operations/MobileStatus/OperationTransferStatus.js",
			"Visible":"/SAPAssetManager/Rules/Operations/MobileStatus/EnableOperationTransfer.js"
        },
        {
			"Title": "$(L,assign)",
			"Visible": "/SAPAssetManager/Rules/Operations/MobileStatus/IsAssignEnableWorkOrderOperation.js",
			"OnPress": "/SAPAssetManager/Rules/Supervisor/Assign/OperationAssignNav.js"
		},
		{
			"Title": "$(L,unassign)",
			"OnPress": "/SAPAssetManager/Rules/Supervisor/UnAssign/OperationUnAssignNav.js",
			"Visible":"/SAPAssetManager/Rules/Operations/MobileStatus/IsUnAssignEnableWorkOrderOperation.js"
		},
		{
			"Title": "$(L,reassign)",
			"OnPress": "/SAPAssetManager/Rules/Supervisor/ReAssign/OperationReAssignNav.js",
			"Visible":"/SAPAssetManager/Rules/Operations/MobileStatus/IsUnAssignEnableWorkOrderOperation.js"
		}
	],
	"_Type": "Action.Type.PopoverMenu"
}