{
  "Animated": true,
  "Duration": 2,
  "Message": "/SAPAssetManager/Rules/Operations/MobileStatus/OperationMobileStatusSuccessMessage.js",
  "IsIconHidden": true,
  "MaxNumberOfLines": 1,
  "_Type": "Action.Type.ToastMessage"
}