{
	"PopoverItems": [
		{
			"Title": "$(L,hold)",
			"OnPress": "/SAPAssetManager/Rules/WorkOrders/MobileStatus/WorkOrderHoldStatus.js"
		},
		{
			"Title": "/SAPAssetManager/Rules/Supervisor/MobileStatus/CompleteReviewCaption.js",
			"OnPress": "/SAPAssetManager/Rules/WorkOrders/MobileStatus/WorkOrderCompleteStatus.js"
		},
		{
			"Title": "$(L,assign)",
			"Visible": "/SAPAssetManager/Rules/WorkOrders/MobileStatus/IsAssignEnableWorkOrder.js",
			"OnPress": "/SAPAssetManager/Rules/Supervisor/Assign/WorkOrderAssignNav.js"
		},
		{
			"Title": "$(L,unassign)",
			"Visible": "/SAPAssetManager/Rules/WorkOrders/MobileStatus/IsUnAssignOrReAssignEnableWorkOrder.js",
			"OnPress": "/SAPAssetManager/Rules/Supervisor/UnAssign/WorkOrderUnAssignNav.js"
		},
		{
			"Title": "$(L,reassign)",
			"Visible": "/SAPAssetManager/Rules/WorkOrders/MobileStatus/IsUnAssignOrReAssignEnableWorkOrder.js",
			"OnPress": "/SAPAssetManager/Rules/Supervisor/ReAssign/WorkOrderReAssignNav.js"
		}
	],
	"_Type": "Action.Type.PopoverMenu"
}