{
	"Target": {
        "EntitySet": "/SAPAssetManager/Rules/Classification/Characteristics/Update/CharacteristicsUpdateEntitySet.js",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink":  "/SAPAssetManager/Rules/Classification/Characteristics/Delete/CharacteristicDeleteReadLink.js"
    },
	"Headers": {
		"OfflineOData.TransactionID": "/SAPAssetManager/Rules/Classification/Characteristics/Update/CharacteristicsUpdateTrasactionId.js"
	},
	"_Type": "Action.Type.ODataService.DeleteEntity",
	"OnSuccess": "/SAPAssetManager/Rules/Classification/Characteristics/Create/CharacteristicCRUD.js",
	"ValidationRule": "/SAPAssetManager/Rules/Classification/Characteristics/Validation/CharacterisitcsValidation.js",
    "OnFailure": "/SAPAssetManager/Rules/Classification/Characteristics/Update/CharacteristicUpdateOnFailure.js"
}