{
    "_Type": "Action.Type.ToastMessage",
    "Icon": "",
    "Message" : "$(L,sync_success)",
    "IsIconHidden": false,
    "MaxNumberOfLines": 2,
    "Duration": 3,
    "Animated": true,
    "OnSuccess": "/SAPAssetManager/Rules/DigitalSignature/DigitalSignatureCommit.js"
}