{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target": {
        "EntitySet": "MaterialDocItems",
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties": {
        "MatDocItem": "/SAPAssetManager/Rules/Inventory/MaterialDocumentItem/GetMaterialDocumentItemLocalID.js",
        "MaterialDocNumber": "#Property:TempHeader_Key",
        "MaterialDocYear": "#Property:TempHeader_MaterialDocYear",
        "PurchaseOrderNumber": "#Property:TempLine_PurchaseOrderNumber",
        "PurchaseOrderItem": "#Property:TempLine_PurchaseOrderItem",
        "ReservationNumber": "#Property:TempLine_ReservationNumber",
        "ReservationItemNumber": "#Property:TempLine_ReservationItem",
        "MovementType": "#Property:TempLine_MovementType",
        "Material": "#Property:TempLine_Material",
        "Plant": "#Property:TempLine_Plant",
        "StorageLocation": "#Property:TempLine_StorageLocation",
        "EntryQuantity": "#Property:TempLine_EntryQuantity",
        "EntryUOM": "#Property:TempLine_EntryUOM",
        "UOM": "#Property:TempLine_EntryUOM",
        "GoodsRecipient": "#Property:TempLine_GoodsReceipient",
        "AutoGenerateSerialNumbers": "#Property:TempLine_AutoGenerateSerialNumbers",
        "MovementIndicator": "#Property:TempLine_MovementIndicator",
        "FinalIssue": "#Property:TempLine_DeliveryComplete",
        "ItemText": "#Property:TempLine_ItemText",
        "UnloadingPoint": "#Property:TempLine_UnloadingPoint",
        "GLAccount": "#Property:TempLine_GLAccount",
        "CostCenter": "#Property:TempLine_CostCenter",
        "WBSElement": "#Property:TempLine_WBSElement",
        "OrderNumber": "#Property:TempLine_Order",
        "Network": "#Property:TempLine_Network",
        "NetworkActivity": "#Property:TempLine_Activity",
        "Batch": "#Property:TempLine_Batch",
        "StockType": "#Property:TempLine_StockType",
        "ValuationType": "#Property:TempLine_ValuationType",
        "StorageBin": "#Property:TempLine_StorageBin",
        "MovePlant": "#Property:TempLine_ToPlant",
        "MoveStorageLocation": "#Property:TempLine_ToStorageLocation",
        "MoveBatch": "#Property:TempLine_ToBatch",
        "MovementReason": "#Property:TempLine_MovementReason",
        "ReferenceDocHdr": "#Property:TempLine_ReferenceDocHdr",
        "ReferenceDocYear": "#Property:TempLine_ReferenceDocYear",
        "ReferenceDocItem": "#Property:TempLine_ReferenceDocItem"
    },
    "Headers": {
        "OfflineOData.RemoveAfterUpload": "true",
        "OfflineOData.TransactionID": "#Property:TempHeader_Key"
    },
    "CreateLinks": "/SAPAssetManager/Rules/Inventory/MaterialDocumentItem/MaterialDocumentItemCreateLinks.js",
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action"
}