{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/WorkOrders/Meter/Periodic/MetersListView.page",
    "ShowActivityIndicator" : true,
    "ActivityIndicatorText" : " "
}
