{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target":
    {
        "EntitySet" : "CatsTimesheets",
        "Service" : "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties":
    {
        "Counter": "/SAPAssetManager/Rules/TimeSheets/GenerateTimeEntryID.js",
        "Date": "/SAPAssetManager/Rules/TimeSheets/CreateUpdate/TimeSheetCreateUpdateDate.js",
        "Hours": "/SAPAssetManager/Rules/TimeSheets/CreateUpdate/TimeSheetCreateUpdateHours.js",
        "AttendAbsenceType": "/SAPAssetManager/Rules/TimeSheets/CreateUpdate/TimeSheetCreateUpdateAttAbsType.js",
        "ActivityType": "/SAPAssetManager/Rules/TimeSheets/CreateUpdate/TimeSheetCreateUpdateActivityType.js",
        "Workcenter": "/SAPAssetManager/Rules/TimeSheets/CreateUpdate/TimeSheetCreateUpdateWorkCenter.js",
        "PersonnelNumber": "/SAPAssetManager/Rules/TimeSheets/CreateUpdate/TimeSheetCreateUpdatePersonnelNumber.js",
        "ControllerArea": "/SAPAssetManager/Rules/TimeSheets/CreateUpdate/TimeSheetCreateUpdateControllerArea.js"
    },
    "Headers": {
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/TimeSheets/GenerateTimeEntryID.js",
        "OfflineOData.RemoveAfterUpload": "true"        
    },
    "CreateLinks": "/SAPAssetManager/Rules/TimeSheets/CreateUpdate/TimeSheetCreateUpdateCreateLinks.js",
    "OnSuccess" : "/SAPAssetManager/Rules/ClockInClockOut/TimeSheets/TimeSheetSuccess.js",
    "OnFailure": "/SAPAssetManager/Actions/TimeSheets/TimeSheetEntryFailureMessage.action",
    "ValidationRule": "/SAPAssetManager/Rules/TimeSheets/Entry/CreateUpdate/TimeSheetEntryCreateUpdateValidation.js",
    "ActionResult": {
        "_Name": "actionResult"
    }
}