{
    "RequiredFields": ["EquipmentPicker"],
    "_Type": "Action.Type.CheckRequiredFields",
    "OnSuccess": "/SAPAssetManager/Rules/Equipment/Installation/EquipmentInstallationChangeSet.js",
    "OnFailure": "/SAPAssetManager/Rules/Common/UpdateRequiredFailed.js"
}