{
    "Properties":
    {
        "SuperiorEquip": "",
        "FuncLocIdIntern": ""
    },
    "DeleteLinks" : "/SAPAssetManager/Rules/Equipment/Uninstall/UninstallDeleteLinks.js",
    "Target":
    {
        "EntitySet": "MyEquipments",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink": "MyEquipments('{{#Property:Item/#Property:ReturnValue}}')"
    },
    "Headers":
	{
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Equipment/Installation/EquipmentOrFLOCTransactionID.js",
        "Transaction.Ignore": "true"
    },
    "_Type": "Action.Type.ODataService.UpdateEntity"
} 