{
    "Message": "$(L, odata_init_sync_failed)",
    "Duration": 9999,
    "Animated": true,
    "ActionLabel": "/SAPAssetManager/Rules/Common/SyncFailure.js",
    "OnActionLabelPress": "/SAPAssetManager/Rules/Common/SyncFailureNav.js",
    "DismissBannerOnAction": true,
    "_Type": "Action.Type.BannerMessage"
}
