{
    "_Type": "Action.Type.Message",
    "Title": "$(L, dismantle_equipment)",
    "Message": "$(L, dismantle_equipment_Fix_Message)",
    "OKCaption": "$(L,ok)",
    "CancelCaption": "$(L,cancel)"
}