{
    "_Type": "Action.Type.Message",
    "Title": "#ClientData/#Property:DialogTitle",
    "Message": "#ClientData/#Property:DialogMessage",
    "OKCaption": "#ClientData/#Property:DialogOkCaption",
    "CancelCaption": "#ClientData/#Property:DialogCancelCaption"
}