{
	"_Type": "Action.Type.Message",
	"Message": "$(L, no_updated_needed)",
	"Title": "$(L, app_update)",
	"OKCaption": "$(L, ok)",
	"OnSuccess": "/SAPAssetManager/Rules/OData/Download/DownloadDefiningRequestsIfNeeded.js"
}