{
    "OnFailure": "/SAPAssetManager/Rules/Common/UpdateRequiredFailed.js",
    "OnSuccess": "/SAPAssetManager/Actions/Logger/UploadLogging.action",
    "RequiredFields": [
        "LogLevelLstPkr"
    ],
    "_Type": "Action.Type.CheckRequiredFields",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : " "
}
