{
    "Target":
    {
        "EntitySet": "Devices",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "EditLink": "{{#Property:Device_Nav/#Property:@odata.editLink}}"
    },
    "OnSuccess": "/SAPAssetManager/Actions/Meters/Discard/DiscardInstall.action",
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/DeleteEntityFailureMessage.action",
    "_Type": "Action.Type.OfflineOData.UndoPendingChanges"
}