{
    "Target":
    {
        "EntitySet": "MyEquipObjectStatuses",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "EditLink": "{{#Property:@odata.editLink}}/Device_Nav/Equipment_Nav/ObjectStatus_Nav"
    },
    "_Type": "Action.Type.OfflineOData.UndoPendingChanges",
    "OnSuccess": "/SAPAssetManager/Rules/ApplicationEvents/AutoSync/actions/DiscardEntitySuccessMessageWithAutoSync.js",
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/DeleteEntityFailureMessage.action"
}