{
     "Target": {
         "EntitySet": "/SAPAssetManager/Rules/Equipment/DocumentAddEditEntitySet.js",
         "Service": "/SAPAssetManager/Services/AssetManager.service",
         "ReadLink" : "/SAPAssetManager/Rules/Equipment/DocumentAddEditEntitySetReadLink.js"
     },
     "Properties" : {		
     },
     "OnSuccess": "/SAPAssetManager/Rules/Documents/Create/DocumentCreateDelete.js",
     "ValidationRule": "/SAPAssetManager/Rules/Equipment/DocumentAddEditValidation.js",
     "_Type": "Action.Type.ODataService.UpdateEntity"
 }