{
    "Actions": [
        "/SAPAssetManager/Actions/Meters/SetBlockedFlag.action",
        "/SAPAssetManager/Actions/Meters/DisconnectMeter.action"
    ],
    "OnSuccess": "/SAPAssetManager/Rules/Meter/PromptReading.js",
    "OnFailure" : "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnFailure.js",
    "Target": {
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "_Type": "Action.Type.ODataService.ChangeSet"
}
