{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target":
    {
        "EntitySet": "Devices",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink": "#Property:Device_Nav/#Property:@odata.readLink"
    },
    "Properties":
    {
        "DeviceBlocked" : false
    },
	"Headers":
	{
        "Transaction.Ignore": "true"
    }
}