{
    "_Type" : "Action.Type.Filter",
    "PageToOpen" : "/SAPAssetManager/Pages/Expenses/ExpensesFilter.page",
    "Filterable" : "#Page:ExpensesListViewPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
     }
}