{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Target": {
		"EntitySet": "MyNotifGeometries",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"Properties": {
		"ObjectType": "NO1",
		"ObjectKey": "/SAPAssetManager/Rules/Geometries/ObjectKeyFromPage.js",
        "NotificationNumber":"/SAPAssetManager/Rules/Geometries/ObjectKeyFromPage.js"
	},
	"Headers": {
        "OfflineOData.RemoveAfterUpload": "true",
		"Transaction.Ignore": "true",
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Geometries/ObjectKeyFromPage.js"
    },
	"RequestOptions": {
		"UnmodifiableRequest": true,
		"SendEmptyUpdate": true
	},
	"CreateLinks": [
		{
			"Property" : "Geometry",
			"Target":
			{
				"EntitySet" : "Geometries", 
				"ReadLink" : "/SAPAssetManager/Rules/Geometries/NewGeometryReadLink.js"
			}
		}, 
		{
			"Property" : "NotifHeader",
			"Target":
			{
				"EntitySet" : "MyNotificationHeaders",
				"ReadLink" :"/SAPAssetManager/Rules/Geometries/ReadLinkFromPage.js"
			}
		}
	],
	"OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action"
}