{
	"_Type": "Action.Type.Filter",
	"PageToOpen": "/SAPAssetManager/Pages/ServiceOrders/Item/ServiceItemFilter.page",
	"Filterable": "#Page:ServiceItemsListViewPage/#Control:SectionedTable",
	"ActionResult": {
		"_Name": "filterResult"
	}
}