{
    "_Type" : "Action.Type.Filter",
    "PageToOpen" : "/SAPAssetManager/Pages/WCM/SafetyCertificates/SafetyCertificatesFilter.page",
    "Filterable" : "#Page:SafetyCertificatesListViewPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}