{
    "_Type" : "Action.Type.Filter",
    "PageToOpen" : "/SAPAssetManager/Pages/WCM/WorkApprovals/WorkApprovalsFilter.page",
    "Filterable" : "#Page:WorkApprovalsListViewPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}