{
    "OnFailure": "/SAPAssetManager/Rules/Common/UpdateRequiredFailed.js",
    "OnSuccess": "/SAPAssetManager/Rules/LAM/CreateUpdate/LAMValuesCreateUpdateOnSave.js",
    "RequiredFields": [
        "Length",
        "StartPoint",
        "EndPoint",
        "UOMLstPkr"
    ],
    "_Type": "Action.Type.CheckRequiredFields",
    "ShowActivityIndicator": true,
    "ValidationRule": "/SAPAssetManager/Rules/LAM/CharacteristicLAMValuesCreateUpdateValidation.js",
    "ActivityIndicatorText" : "  "
}