{
    "Actions": [
        "/SAPAssetManager/Actions/Parts/BOM/BOMCreateUpdateNav.action"
    ],
    "OnSuccess": "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnSuccess.js",
    "Target": {
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "_Type": "Action.Type.ODataService.ChangeSet"
}