{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "/SAPAssetManager/Rules/Notes/NoteGetEntitySet.js",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink": "/SAPAssetManager/Rules/Notes/NoteReadlink.js"  
    },
    "Properties": {
        "NotificationNumber": "/SAPAssetManager/Rules/Notifications/ChangesetSwitchNotificationID.js",
        "ItemNumber": "/SAPAssetManager/Rules/Notifications/Item/GenerateNotificationItemID.js",
        "TaskSequenceNumber": "/SAPAssetManager/Rules/Notifications/Item/Task/GenerateNotificationItemTaskID.js",
        "NewTextString": "/SAPAssetManager/Rules/Notes/NoteUpdateNewTextString.js",
        "TextString": "/SAPAssetManager/Rules/Notes/NoteUpdateTextString.js"
    },
    "Headers": {
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Notifications/ChangesetSwitchNotificationID.js"
    },
    "OnSuccess": "/SAPAssetManager/Rules/Notes/SubOperation/NotificationCreateNoteCreate.js",
    "OnFailure": "/SAPAssetManager/Actions/Notes/NoteCreateFailureMessage.action",
    "UpdateLinks": "/SAPAssetManager/Rules/Notes/NoteCreateLinks.js",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  "
}
