{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Target": {
		"EntitySet" : "MyWorkOrderObjectLists",
		"Service" : "/SAPAssetManager/Services/AssetManager.service"
	},
	"Headers": {
        "OfflineOData.RemoveAfterUpload": "true",
		"OfflineOData.TransactionID": "#Property:LocalNotificationId"
    },
	"Properties": {
		"NotifNum": "#Property:LocalNotificationId",
        "OrderId": "#Property:OrderId",
        "ObjectListNum": "/SAPAssetManager/Rules/ObjectList/ObjectListNum.js",
		"ObjectListCounter": "/SAPAssetManager/Rules/ObjectList/ObjectListCounter.js"
	},
	"CreateLinks": "/SAPAssetManager/Rules/ObjectList/ObjectListCreateLinksNotifFromWorkOrder.js",
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action"
}
