{
    "PopoverItems": [
        {
            "Title": "$(L,issue_part)",
            "OnPress": "/SAPAssetManager/Rules/Parts/Issue/PartIssueNav.js",
            "Visible": "/SAPAssetManager/Rules/Parts/Issue/IssueEnable.js"
        },
        {
            "Title" : "/SAPAssetManager/Rules/Notes/NotePopoverSelectionText.js",
            "OnPress": "/SAPAssetManager/Rules/Notes/NoteCreateNav.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}