{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target": {
        "EntitySet": "MaterialDocItems",
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties": {
        "MatDocItem":"/SAPAssetManager/Rules/Parts/Issue/LineItem/PartIssueLineItemLocalID.js",
        "OrderNumber": "/SAPAssetManager/Rules/Parts/Issue/LineItem/PartMovementLineItemOrderNumber.js",
        "MovementType": "/SAPAssetManager/Rules/Parts/Issue/LineItem/PartIssueLineItemMovementType.js",
        "ReservationNumber": "/SAPAssetManager/Rules/Parts/Issue/LineItem/PartMovementLineItemReservationNumber.js",
        "ReservationItemNumber": "/SAPAssetManager/Rules/Parts/Issue/LineItem/PartMovementLineItemReservationItemNumber.js",
        "Material": "/SAPAssetManager/Rules/Parts/Issue/LineItem/PartMovementLineItemMaterial.js",
        "Plant": "/SAPAssetManager/Rules/Parts/Issue/LineItem/PartMovementLineItemPlant.js",
        "StorageLocation": "/SAPAssetManager/Rules/Parts/Issue/LineItem/PartMovementLineItemStorageLocation.js",
        "EntryQuantity": "/SAPAssetManager/Rules/Parts/Issue/LineItem/PartIssueLineItemQuantity.js",
        "EntryUOM": "/SAPAssetManager/Rules/Parts/Issue/LineItem/PartMovementLineItemUOM.js",
        "AutoGenerateSerialNumbers":"/SAPAssetManager/Rules/Parts/Issue/LineItem/PartIssueLineItemAutoGenerateSerial.js",
        "Batch": "/SAPAssetManager/Rules/Parts/Issue/Header/PartIssueHeaderBatch.js",
        "ValuationType": "/SAPAssetManager/Rules/Parts/Issue/LineItem/PartLineItemValuationType.js"
    },
    "Headers": {
        "OfflineOData.RemoveAfterUpload": "true",
        "OfflineOData.TransactionID": "#ClientData/#Property:LocalMatDocId"
    },
    "CreateLinks": "/SAPAssetManager/Rules/Parts/Issue/CreateUpdate/PartIssueCreateLineItemLinks.js",
    "OnSuccess": "/SAPAssetManager/Rules/Parts/Issue/CreateUpdate/PartIssueCreateLineItemSuccess.js",
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action"
}