{
    "_Type": "Action.Type.Message",
    "Title": "$(L,warning)",
    "Message": "$(L,validation_greater_than_unrestricted_quantity)",
    "OKCaption": "$(L,ok)",
    "CancelCaption": "$(L,cancel)"
}