{
	"PopoverItems": 
	[{
		"Title": "$(L,add_item)",
		"OnPress": "/SAPAssetManager/Rules/Notifications/Item/CreateUpdate/NotificationItemCreateNav.js",
		"Visible": "/SAPAssetManager/Rules/UserAuthorizations/Notifications/EnableNotificationEdit.js"

	},
	{
		"Title": "$(L,add_task)",
		"OnPress": "/SAPAssetManager/Rules/Notifications/Task/CreateUpdate/NotificationTaskCreateNav.js",
		"Visible": "/SAPAssetManager/Rules/Notifications/Task/CreateUpdate/EnableNotificationTaskCreate.js"
	},
	{
		"Title": "$(L,add_activity)",
		"OnPress": "/SAPAssetManager/Rules/Notifications/Activity/CreateUpdate/NotificationActivityCreateNav.js",
		"Visible": "/SAPAssetManager/Rules/UserAuthorizations/Notifications/EnableNotificationEdit.js"
	},
	{
		"Title": "$(L,add_workorder)",
		"OnPress": "/SAPAssetManager/Rules/WorkOrders/CreateUpdate/WorkOrderCreateFromNotificationNav.js",
		"Visible": "/SAPAssetManager/Rules/Notifications/Details/NotificationCreateWorkOrderVisible.js"
	},
	{
		"Title" : "/SAPAssetManager/Rules/Notes/NotePopoverSelectionText.js",
		"OnPress" : "/SAPAssetManager/Rules/Notes/NoteCreateNav.js",
		"Visible": "/SAPAssetManager/Rules/UserAuthorizations/Notifications/EnableNotificationEdit.js"
	},
	{
		"Title" : "$(L,add_reminder)",
		"OnPress" : "/SAPAssetManager/Rules/Reminders/ReminderCreateNav.js",
		"Visible": "/SAPAssetManager/Rules/UserAuthorizations/Notifications/EnableNotificationEdit.js"
	}],
	"_Type": "Action.Type.PopoverMenu"
}