{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Headers": {
    	"OfflineOData.NonMergeable": true,
		"transaction.omdo_id": "/SAPAssetManager/Rules/MobileStatus/MobileStatusS4TransactionMdoHeader.js"    
	},
	"Target":{
		"EntitySet": "PMMobileStatuses",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"Properties": {
		"MobileStatus": "/SAPAssetManager/Rules/MobileStatus/MobileStatusReceived.js",
		"ObjectType": "/SAPAssetManager/Rules/MobileStatus/MobileStatusServiceOrderObjectType.js",
		"ObjectKey": "/SAPAssetManager/Rules/MobileStatus/MobileStatusSetReceivedObjectKey.js",
        "EffectiveTimestamp": "/SAPAssetManager/Rules/DateTime/CurrentDateTime.js",
		"BusinessObjectType": "/SAPAssetManager/Rules/ServiceOrders/ServiceOrderObjectType.js",
		"SystemStatusCode": "/SAPAssetManager/Rules/ServiceOrders/GetReleasedStatusCode.js"
	},
	"CreateLinks": [{
        "Property": "S4ServiceOrder_Nav",
        "Target": {
			"EntitySet" : "S4ServiceOrders",
			"ReadLink": "/SAPAssetManager/Rules/MobileStatus/MobileStatusLocalServiceOrderReadLink.js"
        }
      },
	  {
		  "Property": "OverallStatusCfg_Nav",
		  "Target": {
			  "EntitySet": "EAMOverallStatusConfigs",
			  "QueryOptions": "/SAPAssetManager/Rules/MobileStatus/ServiceOrderOverallStatusConfigQueryOptions.js"
		  }
	  }
    ],
	"OnSuccess": "/SAPAssetManager/Actions/MobileStatus/MobileStatusServiceItemSetReceived.action",
	"OnFailure" : "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnFailure.js",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText" : " "
}
