{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Headers": {
    	"OfflineOData.NonMergeable": true,
		"transaction.omdo_id": "/SAPAssetManager/Rules/MobileStatus/MobileStatusS4TransactionMdoHeader.js"
	},
	"Target":{
		"EntitySet": "PMMobileStatuses",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"Properties": {
		"MobileStatus": "/SAPAssetManager/Rules/MobileStatus/MobileStatusReceived.js",
		"ObjectType": "/SAPAssetManager/Rules/MobileStatus/MobileStatusServiceItemObjectType.js",
		"ObjectKey": "/SAPAssetManager/Rules/MobileStatus/MobileStatusSetReceivedObjectKeyToItem.js",
        "EffectiveTimestamp": "/SAPAssetManager/Rules/DateTime/CurrentDateTime.js",
		"BusinessObjectType": "/SAPAssetManager/Rules/ServiceOrders/ServiceItemObjectType.js",
		"S4ItemNum": "/SAPAssetManager/Rules/ServiceItems/CreateUpdate/Data/GetServiceItemLocalID.js"
	},
	"CreateLinks": [{
        "Property": "S4ServiceItem_Nav",
        "Target": {
			"EntitySet" : "S4ServiceItems",
			"ReadLink": "/SAPAssetManager/Rules/MobileStatus/MobileStatusLocalServiceItemReadLink.js"
        }
      },
	  {
		  "Property": "OverallStatusCfg_Nav",
		  "Target": {
			  "EntitySet": "EAMOverallStatusConfigs",
			  "QueryOptions": "/SAPAssetManager/Rules/MobileStatus/ServiceItemOverallStatusConfigQueryOptions.js"
		  }
	  }
    ],
	"OnSuccess": "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnSuccess.js",
	"OnFailure" : "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnFailure.js",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText" : " "
}
