{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target": {
        "EntitySet": "MyWorkOrderPartners",
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties": {
        "OrderId": "/SAPAssetManager/Rules/WorkOrders/CreateUpdate/WorkOrderLocalID.js",
        "Partner": "#Page:WorkOrderCreateUpdatePage/#Control:SoldToPartyLstPkr/#SelectedValue",
        "PartnerFunction": "/SAPAssetManager/Rules/ServiceOrders/Partner/ServiceOrderPartnerFunction.js"
    },
    "Headers": {
        "OfflineOData.RemoveAfterUpload": "true",
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/WorkOrders/CreateUpdate/WorkOrderLocalID.js"
    },
    "CreateLinks": "/SAPAssetManager/Rules/ServiceOrders/Partner/ServiceOrderPartnerCreateUpdateLinks.js",
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : " "
}
