{
	"_Type": "Action.Type.CheckRequiredFields",
	"RequiredFields": [
		"DescriptionNote",
		"PrioritySeg",
		"SoldToPartyLstPkr",
		"SalesOrgLstPkr",
		"ServiceOrgLstPkr",
		"BillToPartyLstPkr",
		"DistChannelLstPkr",
		"DivisionLstPkr"
	],
	"OnFailure": "/SAPAssetManager/Rules/Common/UpdateRequiredFailed.js",
	"OnSuccess": "/SAPAssetManager/Rules/ServiceOrders/CreateUpdate/ServiceOrderCreateUpdateOnCommit.js",
	"ValidationRule": "/SAPAssetManager/Rules/Common/Validation/TechnicalObjectCreateUpdateValidation.js",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  "
}