{
    "Headers": {
        "OfflineOData.NonMergeable": true
    },
    "Properties": {
        "ObjectKey": "/SAPAssetManager/Rules/MobileStatus/MobileStatusSubOperationObjectKey.js",
        "ObjectType": "/SAPAssetManager/Rules/MobileStatus/MobileStatusSubOperationObjectType.js",
        "MobileStatus": "/SAPAssetManager/Rules/MobileStatus/MobileStatusHold.js",
        "EffectiveTimestamp": "/SAPAssetManager/Rules/DateTime/EndDateTime.js",
        "CreateUserGUID": "/SAPAssetManager/Rules/UserPreferences/UserPreferencesUserGuidOnCreate.js",
        "CreateUserId": "/SAPAssetManager/Rules/MobileStatus/GetSAPUserId.js"
    },
    "Target": {
        "EntitySet": "PMMobileStatuses",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink" : "/SAPAssetManager/Rules/MobileStatus/MobileStatusReadLink.js"
    },
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  ",
    "ActionResult" : {"_Name" : "SubOperationMobileStatusHoldUpdate"}
}
