{
	"PopoverItems":
	[{
		"Title": "$(L,add_to_order)",
        "OnPress": "/SAPAssetManager/Rules/Parts/PartCreateUpdateNavFromList.js"
	},
	{
		"Title": "$(L,stock_transfer)",
        "OnPress": "/SAPAssetManager/Rules/Inventory/Stock/Transfer/TransferFromList.js"
	},
	{
		"Title": "$(L,recent_transfers)",
        "OnPress": "/SAPAssetManager/Actions/Inventory/Stock/RecentTransfersNav.action"
	}
	],
	"_Type": "Action.Type.PopoverMenu"
}